
t = task "A" do |t|
  c = 10.times.map do |i|
    task "C#{i}" do |t|
      sh "echo #{t.name}; sleep 1"
    end.name
  end

  (task "B" => c).invoke
end

puts "task.location=#{task.location}"

task :default => ["A"]
